#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ranken")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOwner(Owner instance);
    partial void UpdateOwner(Owner instance);
    partial void DeleteOwner(Owner instance);
    partial void InsertCASA(CASA instance);
    partial void UpdateCASA(CASA instance);
    partial void DeleteCASA(CASA instance);
    partial void InsertMortgage(Mortgage instance);
    partial void UpdateMortgage(Mortgage instance);
    partial void DeleteMortgage(Mortgage instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::ROI.Properties.Settings.Default.RankenConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Owner> Owners
		{
			get
			{
				return this.GetTable<Owner>();
			}
		}
		
		public System.Data.Linq.Table<CASA> CASAs
		{
			get
			{
				return this.GetTable<CASA>();
			}
		}
		
		public System.Data.Linq.Table<Mortgage> Mortgages
		{
			get
			{
				return this.GetTable<Mortgage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Owner")]
	public partial class Owner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _address;
		
		private string _ownerName;
		
		private System.Nullable<decimal> _bracket;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnownerNameChanging(string value);
    partial void OnownerNameChanged();
    partial void OnbracketChanging(System.Nullable<decimal> value);
    partial void OnbracketChanged();
    #endregion
		
		public Owner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownerName", DbType="NVarChar(MAX)")]
		public string ownerName
		{
			get
			{
				return this._ownerName;
			}
			set
			{
				if ((this._ownerName != value))
				{
					this.OnownerNameChanging(value);
					this.SendPropertyChanging();
					this._ownerName = value;
					this.SendPropertyChanged("ownerName");
					this.OnownerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bracket", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> bracket
		{
			get
			{
				return this._bracket;
			}
			set
			{
				if ((this._bracket != value))
				{
					this.OnbracketChanging(value);
					this.SendPropertyChanging();
					this._bracket = value;
					this.SendPropertyChanged("bracket");
					this.OnbracketChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CASA")]
	public partial class CASA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _address;
		
		private System.Nullable<decimal> _area;
		
		private System.Nullable<decimal> _bedrooms;
		
		private System.Nullable<decimal> _bathrooms;
		
		private System.Nullable<decimal> _garage;
		
		private string _basement;
		
		private System.Nullable<decimal> _appreciationRate;
		
		private System.Nullable<int> _OwnerID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnareaChanging(System.Nullable<decimal> value);
    partial void OnareaChanged();
    partial void OnbedroomsChanging(System.Nullable<decimal> value);
    partial void OnbedroomsChanged();
    partial void OnbathroomsChanging(System.Nullable<decimal> value);
    partial void OnbathroomsChanged();
    partial void OngarageChanging(System.Nullable<decimal> value);
    partial void OngarageChanged();
    partial void OnbasementChanging(string value);
    partial void OnbasementChanged();
    partial void OnappreciationRateChanging(System.Nullable<decimal> value);
    partial void OnappreciationRateChanged();
    partial void OnOwnerIDChanging(System.Nullable<int> value);
    partial void OnOwnerIDChanged();
    #endregion
		
		public CASA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bedrooms", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> bedrooms
		{
			get
			{
				return this._bedrooms;
			}
			set
			{
				if ((this._bedrooms != value))
				{
					this.OnbedroomsChanging(value);
					this.SendPropertyChanging();
					this._bedrooms = value;
					this.SendPropertyChanged("bedrooms");
					this.OnbedroomsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bathrooms", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> bathrooms
		{
			get
			{
				return this._bathrooms;
			}
			set
			{
				if ((this._bathrooms != value))
				{
					this.OnbathroomsChanging(value);
					this.SendPropertyChanging();
					this._bathrooms = value;
					this.SendPropertyChanged("bathrooms");
					this.OnbathroomsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_garage", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> garage
		{
			get
			{
				return this._garage;
			}
			set
			{
				if ((this._garage != value))
				{
					this.OngarageChanging(value);
					this.SendPropertyChanging();
					this._garage = value;
					this.SendPropertyChanged("garage");
					this.OngarageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basement", DbType="NVarChar(MAX)")]
		public string basement
		{
			get
			{
				return this._basement;
			}
			set
			{
				if ((this._basement != value))
				{
					this.OnbasementChanging(value);
					this.SendPropertyChanging();
					this._basement = value;
					this.SendPropertyChanged("basement");
					this.OnbasementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appreciationRate", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> appreciationRate
		{
			get
			{
				return this._appreciationRate;
			}
			set
			{
				if ((this._appreciationRate != value))
				{
					this.OnappreciationRateChanging(value);
					this.SendPropertyChanging();
					this._appreciationRate = value;
					this.SendPropertyChanged("appreciationRate");
					this.OnappreciationRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", DbType="Int")]
		public System.Nullable<int> OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this.OnOwnerIDChanging(value);
					this.SendPropertyChanging();
					this._OwnerID = value;
					this.SendPropertyChanged("OwnerID");
					this.OnOwnerIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mortgage")]
	public partial class Mortgage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<decimal> _LtvRatio;
		
		private System.Nullable<decimal> _LoanAmount;
		
		private System.Nullable<decimal> _MonthlyPayment;
		
		private System.Nullable<int> _Months;
		
		private System.Nullable<decimal> _InterestRate;
		
		private System.Nullable<decimal> _LoanOriginationFees;
		
		private System.Nullable<decimal> _DownPayment;
		
		private System.Nullable<decimal> _DepreciableClosingCosts;
		
		private System.Nullable<decimal> _OtherClosingCosts;
		
		private System.Nullable<decimal> _PurchasePrice;
		
		private int _PropertyID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLtvRatioChanging(System.Nullable<decimal> value);
    partial void OnLtvRatioChanged();
    partial void OnLoanAmountChanging(System.Nullable<decimal> value);
    partial void OnLoanAmountChanged();
    partial void OnMonthlyPaymentChanging(System.Nullable<decimal> value);
    partial void OnMonthlyPaymentChanged();
    partial void OnMonthsChanging(System.Nullable<int> value);
    partial void OnMonthsChanged();
    partial void OnInterestRateChanging(System.Nullable<decimal> value);
    partial void OnInterestRateChanged();
    partial void OnLoanOriginationFeesChanging(System.Nullable<decimal> value);
    partial void OnLoanOriginationFeesChanged();
    partial void OnDownPaymentChanging(System.Nullable<decimal> value);
    partial void OnDownPaymentChanged();
    partial void OnDepreciableClosingCostsChanging(System.Nullable<decimal> value);
    partial void OnDepreciableClosingCostsChanged();
    partial void OnOtherClosingCostsChanging(System.Nullable<decimal> value);
    partial void OnOtherClosingCostsChanged();
    partial void OnPurchasePriceChanging(System.Nullable<decimal> value);
    partial void OnPurchasePriceChanged();
    partial void OnPropertyIDChanging(int value);
    partial void OnPropertyIDChanged();
    #endregion
		
		public Mortgage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LtvRatio", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> LtvRatio
		{
			get
			{
				return this._LtvRatio;
			}
			set
			{
				if ((this._LtvRatio != value))
				{
					this.OnLtvRatioChanging(value);
					this.SendPropertyChanging();
					this._LtvRatio = value;
					this.SendPropertyChanged("LtvRatio");
					this.OnLtvRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoanAmount", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> LoanAmount
		{
			get
			{
				return this._LoanAmount;
			}
			set
			{
				if ((this._LoanAmount != value))
				{
					this.OnLoanAmountChanging(value);
					this.SendPropertyChanging();
					this._LoanAmount = value;
					this.SendPropertyChanged("LoanAmount");
					this.OnLoanAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthlyPayment", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> MonthlyPayment
		{
			get
			{
				return this._MonthlyPayment;
			}
			set
			{
				if ((this._MonthlyPayment != value))
				{
					this.OnMonthlyPaymentChanging(value);
					this.SendPropertyChanging();
					this._MonthlyPayment = value;
					this.SendPropertyChanged("MonthlyPayment");
					this.OnMonthlyPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Months", DbType="Int")]
		public System.Nullable<int> Months
		{
			get
			{
				return this._Months;
			}
			set
			{
				if ((this._Months != value))
				{
					this.OnMonthsChanging(value);
					this.SendPropertyChanging();
					this._Months = value;
					this.SendPropertyChanged("Months");
					this.OnMonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InterestRate", DbType="Decimal(13,5)")]
		public System.Nullable<decimal> InterestRate
		{
			get
			{
				return this._InterestRate;
			}
			set
			{
				if ((this._InterestRate != value))
				{
					this.OnInterestRateChanging(value);
					this.SendPropertyChanging();
					this._InterestRate = value;
					this.SendPropertyChanged("InterestRate");
					this.OnInterestRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoanOriginationFees", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> LoanOriginationFees
		{
			get
			{
				return this._LoanOriginationFees;
			}
			set
			{
				if ((this._LoanOriginationFees != value))
				{
					this.OnLoanOriginationFeesChanging(value);
					this.SendPropertyChanging();
					this._LoanOriginationFees = value;
					this.SendPropertyChanged("LoanOriginationFees");
					this.OnLoanOriginationFeesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownPayment", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> DownPayment
		{
			get
			{
				return this._DownPayment;
			}
			set
			{
				if ((this._DownPayment != value))
				{
					this.OnDownPaymentChanging(value);
					this.SendPropertyChanging();
					this._DownPayment = value;
					this.SendPropertyChanged("DownPayment");
					this.OnDownPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepreciableClosingCosts", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> DepreciableClosingCosts
		{
			get
			{
				return this._DepreciableClosingCosts;
			}
			set
			{
				if ((this._DepreciableClosingCosts != value))
				{
					this.OnDepreciableClosingCostsChanging(value);
					this.SendPropertyChanging();
					this._DepreciableClosingCosts = value;
					this.SendPropertyChanged("DepreciableClosingCosts");
					this.OnDepreciableClosingCostsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherClosingCosts", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> OtherClosingCosts
		{
			get
			{
				return this._OtherClosingCosts;
			}
			set
			{
				if ((this._OtherClosingCosts != value))
				{
					this.OnOtherClosingCostsChanging(value);
					this.SendPropertyChanging();
					this._OtherClosingCosts = value;
					this.SendPropertyChanged("OtherClosingCosts");
					this.OnOtherClosingCostsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchasePrice", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> PurchasePrice
		{
			get
			{
				return this._PurchasePrice;
			}
			set
			{
				if ((this._PurchasePrice != value))
				{
					this.OnPurchasePriceChanging(value);
					this.SendPropertyChanging();
					this._PurchasePrice = value;
					this.SendPropertyChanged("PurchasePrice");
					this.OnPurchasePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyID", DbType="Int NOT NULL")]
		public int PropertyID
		{
			get
			{
				return this._PropertyID;
			}
			set
			{
				if ((this._PropertyID != value))
				{
					this.OnPropertyIDChanging(value);
					this.SendPropertyChanging();
					this._PropertyID = value;
					this.SendPropertyChanged("PropertyID");
					this.OnPropertyIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
